### ISSUE TITLE
Bug in RTL mode

### ISSUE THREAD

**Issue by amribrahim1** [MaTeMaTuK/gantt-task-react#166]
![Screenshot 2023-02-12 120544](https://user-images.githubusercontent.com/8148579/218304826-9ae57218-3347-4dae-8c0f-1a8293638254.png)

```
Uncaught TypeError: Cannot read properties of undefined (reading 'getTime')                         bar-helper.ts:252 
    at taskXCoordinate (bar-helper.ts:252:1)
    at taskXCoordinateRTL (bar-helper.ts:263:1)
    at convertToBar (bar-helper.ts:157:1)
    at convertToBarTask (bar-helper.ts:102:1)
    at bar-helper.ts:26:1
    at Array.map (<anonymous>)
    at convertToBarTasks (bar-helper.ts:25:1)
    at gantt.tsx:123:1
```
 
I knew that you fixed a crash in rtl mode including `src/helpers/bar-helper.ts`, but it seem that you don't compile this fix to production `dist` !

I had to downgrade to 0.3.8 version to avoid this error.

**Comment by dukinfotech** [comment]
Same here. Please check your data. If the 'Start' value is greater than the 'End' value, this issue could occur.
